config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks"}
  root "posts#index"
  get "pricing", to: "static_pages#pricing"
  resources :posts
  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]

# API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [:create, :destroy]
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def pricing
    # para poder sacar los precios de producto/precio especifico se genera un lookup_key en Rails c:  Stripe::Price.update("price_1JbQeQI2rsCLxTB1zVxsEzJD", lookup_key: "good_year")
    # @pricing = Stripe::Price.list(lookup_keys: ["rp_basic_3800_m", "rp_basic_29900_y", "rp_team_9900_m", "rp_team_74400_y", "rp_enter_19900_m", "rp_enter_150000_y" ], expand: ["data.product"]).data.sort_by {|p| p.unit_amount}

    @pricing_basic = Stripe::Price.list(lookup_keys: ["rp_basic_3800_m", "rp_basic_29900_y"], expand: ["data.product"]).data.sort_by {|p| p.unit_amount}

    @pricing_team = Stripe::Price.list(lookup_keys: ["rp_team_9900_m", "rp_team_74400_y"]).data.sort_by {|p| p.unit_amount}

    @pricing_enter = Stripe::Price.list(lookup_keys: ["rp_enter_19900_m", "rp_enter_150000_y" ], expand: ["data.product"]).data.sort_by {|p| p.unit_amount}



    if current_user.stripe_customer_id
        # <%= link_to t('learn_more'), "https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_32D88BD1qLklliziD7gYQvctJIhWBSQ7&scope=read_write", class: "btn btn-primary" %>
    else
        # customer = Stripe::Customer.create(email: self.email, name: self.fullname)
        # update customer Stripe ID
    end


  end

end

app/views/static_pages/pricing.html.erb
<div style="width: 250px;">
  <%= stripe_connect_button %>
</div>

<h1>Pricing</h1>
<br>
<hr>
<h2>Basic</h2>
    <% @pricing_basic.each do |price| %>
      <b>
        <%= price.lookup_key %>
      </b>
      <small><%= price.id %></small>
      <b>
        <%= price.unit_amount/100 %>
        <%= price.currency %>
        <%= price.recurring.interval %>
      </b>
      <%= link_to "Pay #{price.unit_amount/100} per #{price.recurring.interval}", checkout_create_path(price: price.id), method: :post, remote: true, data: { disable_with: "validating..."} %>
      <br>
    <% end %>
<hr>

<h2>Team</h2>
    <% @pricing_team.each do |price| %>
      <b>
        <%= price.lookup_key %>
      </b>
      <small><%= price.id %></small>
      <b>
        <%= price.unit_amount/100 %>
        <%= price.currency %>
        <%= price.recurring.interval %>
      </b>
      <%= link_to "Pay #{price.unit_amount/100} per #{price.recurring.interval}", checkout_create_path(price: price.id), method: :post, remote: true, data: { disable_with: "validating..."} %>
      <br>
    <% end %>

<hr>
<h2>Enterprise</h2>
    <% @pricing_enter.each do |price| %>
      <b>
        <%= price.lookup_key %>
      </b>
      <small><%= price.id %></small>
      <b>
        <%= price.unit_amount/100 %>
        <%= price.currency %>
        <%= price.recurring.interval %>
      </b>
      <%= link_to "Pay #{price.unit_amount/100} per #{price.recurring.interval}", checkout_create_path(price: price.id), method: :post, remote: true, data: { disable_with: "validating..."} %>
      <br>
    <% end %>