config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks"}
  root "posts#index"
  get "pricing", to: "static_pages#pricing"
  resources :posts
  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]

# API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [:create, :destroy]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaasSubscriptionStripe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <center>
      <h1>Stripe SaaS freemium blog demo</h1>
      <%= link_to "Source code", "https://github.com/evolutioncode-io/saas_subscription_stripe", target: "_blank" %>
    </center>
    <hr>
    <p class="notice" style="background-color: green;"><%= notice %></p>
    <p class="alert" style="background-color: red;"><%= alert %></p>
    <% if user_signed_in? %>
      <%= link_to current_user.email, edit_user_registration_path %>
      <br>
      Stripe customer id:
      <%= current_user.stripe_customer_id %>
      <br>
      Plan:
      <%= current_user.plan %>
      <br>
      Subscription status:
      <%= current_user.subscription_status %>
      <% if current_user.current_period_end.present? %>
        <br>
        Subscription ends:
        <%= current_user.current_period_end.strftime('%d/%m/%Y') %>
      <% end %>
      <br>
      <hr>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      <br>
      <%= link_to "Posts", posts_path %>
      <br>
      <%= link_to "Pricing", pricing_path %>
      <br>
      <%= link_to "Stripe BillingPortal", billing_portal_create_path, method: :post, data: { disable_with: "validating..."} %>
      <br><br>
      <hr>
    <% end %>
    <%= yield %>
  </body>
</html>